default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  timeout: 5000

development:
  <<: *default
  url: <%= "#{ENV.fetch('DATABASE_URL', 'postgresql://localhost/rails_app_development')}#{ENV['TEST_ENV_NUMBER']}" %>

test:
  <<: *default
  url: <%= "#{ENV.fetch('DATABASE_URL', 'postgresql://localhost/rails_app_test')}#{ENV['TEST_ENV_NUMBER']}" %>

production:
  <<: *default
