ruby_app: &ruby_app
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
    - image: circleci/postgres:9.4
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        command: ruby hello_world.rb
        working_directory: ~/repo/{{ .Environment.circleJob }}

version: 2
jobs:
  ruby_app_one:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: ruby hello_world.rb
          working_directory: ~/repo/ruby_app_one
  java_app_one:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: javac HelloWorld.java
          working_directory: ~/repo/{{ .Environment.circleJob }}
      - run:
          command: java HelloWorld
          working_directory: ~/repo/{{ .Environment.circleJob }}
workflows:
  version: 2
  test_all:
    jobs:
      - ruby_app_one
      - java_app_one
