ruby_app: &ruby_app
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        command: |
          cd ~/repo/$CIRCLE_JOB
          ruby hello_world.rb

java_app: &java_app
  docker:
    - image: circleci/openjdk:8
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        command: |
          cd ~/repo/$CIRCLE_JOB
          javac HelloWorld.jav
          java HelloWorld

version: 2
jobs:
  ruby_app_one:
    <<: *ruby_app
  ruby_app_two:
    <<: *ruby_app
  java_app_one:
    <<: *java_app
workflows:
  version: 2
  test_all:
    jobs:
      - ruby_app_one
      - ruby_app_two
      - java_app_one
