ruby_app: &ruby_app
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        command: cd ~/repo/$CIRCLE_JOB && ruby hello_world.rb

version: 2
jobs:
  ruby_app_one_fancy:
    <<: *ruby_app
  ruby_app_one:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: ruby hello_world.rb
          working_directory: ~/repo/ruby_app_one
  java_app_one:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: javac HelloWorld.java
          working_directory: ~/repo/java_app_one
      - run:
          command: java HelloWorld
          working_directory: ~/repo/java_app_one
workflows:
  version: 2
  test_all:
    jobs:
      - ruby_app_one_fancy
      - ruby_app_one
      - java_app_one
