version: 2
jobs:
  ruby_app_one:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.4
    steps:
      - checkout
      - run: cd ruby_app_one
      - run: ruby hello_world.rb
  java_app_one:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: cd java_app_one
      - run: javac HelloWorld.java
      - run: java HelloWorld
workflows:
  version: 2
  test_all:
    jobs:
      - ruby_app_one
      - java_app_one
