version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails_app-{{ checksum "rails_app/Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path rails_app/vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails_app-{{ checksum "rails_app/Gemfile.lock" }}
        paths:
          - rails_app/vendor/bundle

      # Database setup
      - run:
          command: |
            cd rails_app
            bundle exec rake db:create db:schema:load

      # Run rspec in parallel
      - run:
          command: |
            cd rails_app
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails_app-{{ checksum "rails_app/Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path rails_app/vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails_app-{{ checksum "rails_app/Gemfile.lock" }}
        paths:
          - rails_app/vendor/bundle

      - run:
          command: |
            ./build.sh rails_app
            # ecr-login
            # find-or-create ecr repo for rails_app
            # docker push $ecr-repo/rails_app:$git_revision

  deploy:
    steps:
      - checkout
      - run:
          command: |
            cd rails_app
            ./deploy.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
