version: 2
jobs:
  "local_gem-test":
    parallelism: 2
    docker:
      - image: circleci/ruby:2.3.4
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    steps:
      - checkout
      - restore-cache:
          keys:
            - v0-local_gem-deps-{{ checksum "local_gem/local_gem.gemspec" }}
            - v0-local_gem-deps-
      - run:
          name: install dependencies
          command: |
            cd local_gem
            bundle check --path vendor/bundle \
              || bundle install --jobs 4 --path vendor/bundle
      - save-cache:
          key: v0-local_gem-deps-{{ checksum "local_gem/local_gem.gemspec" }}
          paths:
            - local_gem/vendor/bundle
      - run:
          name: run tests
          command: |
            cd local_gem
            export SPEC=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings | tr '\r\n' ' ')
            export SPEC_OPTS="--profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress"
            bundle exec rake
      - store_test_results:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  "rails_app-test":
    parallelism: 2
    docker:
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: rails_app_test
    steps:
      - checkout
      - restore-cache:
          keys:
            - v0-rails_app-deps-{{ checksum "rails_app/Gemfile.lock" }}
            - v0-rails_app-deps-
      - run:
          name: install dependencies
          command: |
            cd rails_app
            bundle check --path vendor/bundle \
              || bundle install --path vendor/bundle
      - save-cache:
          key: v0-rails_app-deps-{{ checksum "rails_app/Gemfile.lock" }}
          paths:
            - rails_app/vendor/bundle
      - run:
          name: run tests
          command: |
            cd rails_app
            export SPEC=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings | tr '\r\n' ' ')
            export SPEC_OPTS="--profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress"
            bundle exec rake
      - store_test_results:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  
  "rails_app-build":
    docker:
      - image: circleci/ruby:2.3.4-node
    steps:
      - checkout
      - restore-cache:
          keys:
            - v0-rails_app-deps-{{ checksum "rails_app/Gemfile.lock" }}
            - v0-rails_app-deps-
      - run:
          name: install dependencies
          command: |
            cd rails_app
            bundle check --path vendor/bundle \
              || bundle install --jobs 4 --path vendor/bundle
      - save-cache:
          key: v0-rails_app-deps-{{ checksum "rails_app/Gemfile.lock" }}
          paths:
            - rails_app/vendor/bundle
      - run:
          name: build tarball
          command: |
            tar -z --exclude='.git' -C rails_app -cf slug.tgz .

workflows:
  version: 2
  "all":
    jobs:
      - local_gem-test
      - rails_app-test
      - rails_app-build
