version: 2
jobs:
  ruby_app_one:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.4
    working_directory: ruby_app_one
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: ruby -e "puts 'hi'"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  java_app_one:
    docker:
      - image: circleci/openjdk:8
    working_directory: java_app_one
    steps:
      - checkout
      - run: javac HelloWorld.java
      - run: java HelloWorld
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
